languageCode = "en-us"
title = "Fibercache"
baseURL = "https://fibercache.com"
theme = "massively"
googleanalytics = ""
disqusShortname = ""
author = "iamrexdev@gmail.com"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"